development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ttt_db
  pool: 5
  user: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ttt_db_test
  pool: 5
  user: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  host: postgres://postgres:rLxmyXYtMwEl8d2@ttt-db.flycast:5432
  database: ttt_db
  pool: 5